server:
    port: 8080

spring:
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
        generate-ddl: true
        hibernate:
          ddl-auto: update
          dialect: org.hibernate.dialect.MySQL5Dialect

    thymeleaf:
        mode: LEGACYHTML5

logging:
  level:
    org.springframework.web: ERROR
    com.raysmond.blog: DEBUG