server:
    port: 8080

spring:
    profiles:
        active: production

    thymeleaf:
        cache: true

    jade4j:
        caching: true

    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
        generate-ddl: true
        hibernate:
          ddl-auto: update
          dialect: org.hibernate.dialect.MySQL5Dialect

    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1/spring_blog_dev
      username: root
      password:

    redis:
      host: localhost
      port: 6379
      default_expire_time: 86400

