server:
    port: 8080

spring:
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
        generate-ddl: true
        hibernate:
          ddl-auto: update
          dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    org.springframework.web: ERROR
    com.raysmond.blog: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  file: /Users/mkyong/application.log